spring.application.name=user-service
# SERVER
server.port=8082

# MONGODB
spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/userdb?authSource=admin
spring.data.mongodb.auto-index-creation=true

# JWT
jwt.secret=my_super_secret_key_which_is_longer_than_64_characters_for_security_123456
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# LOGGING
logging.level.org.springframework.security=DEBUG

# Rabbit MQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123